'use client';

import { useState } from 'react';
import { Sparkles, Check, Zap, Target, Crown, ArrowRight, Menu, X } from 'lucide-react';
import { useRouter } from 'next/navigation';

export default function LandingPage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [faqOpen, setFaqOpen] = useState<number | null>(null);
  const router = useRouter();

  const features = [
    {
      icon: Sparkles,
      title: 'AI-Powered Intelligence',
      description: 'Let AI understand your goals and automatically prioritize your tasks',
    },
    {
      icon: Zap,
      title: 'Morning Routine Optimizer',
      description: 'Start every day with a perfectly planned routine generated by AI',
    },
    {
      icon: Target,
      title: 'Smart Productivity Insights',
      description: 'Real-time analytics that tell you exactly where to focus',
    },
    {
      icon: Crown,
      title: 'Built for Winners',
      description: 'No distractions. No clutter. Just results.',
    },
  ];

  const faqs = [
    {
      q: 'What makes this different from other task managers?',
      a: 'We\'re AI-first. While others bolt on AI as an afterthought, we built our entire platform around intelligent task management from day one. AI understands your context, suggests optimal morning routines, and provides real-time productivity insights.',
    },
    {
      q: 'Who is this for?',
      a: 'High-performing individuals who demand more from their tools. If you\'re serious about productivity and want to leverage AI to get more done in less time, this is for you.',
    },
    {
      q: 'Do I need technical AI knowledge?',
      a: 'Not at all! Our AI works behind the scenes. You just focus on your goals, and the AI handles the intelligent optimization automatically.',
    },
    {
      q: 'Can I try it for free?',
      a: 'Yes! Free plan includes 5 tasks. Upgrade to Premium ($9.99/month) for unlimited tasks and advanced AI features.',
    },
    {
      q: 'How does AI help me be more productive?',
      a: 'AI analyzes your task patterns, suggests optimal morning routines, provides smart task recommendations, and gives real-time productivity insights. It\'s like having a personal productivity coach available 24/7.',
    },
  ];

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Navigation */}
      <nav className="fixed w-full z-50 bg-black/80 backdrop-blur-lg border-b border-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center gap-2">
              <Sparkles className="w-6 h-6 text-purple-500" />
              <span className="text-xl font-bold bg-gradient-to-r from-purple-400 to-pink-600 bg-clip-text text-transparent">
                TaskAI Pro
              </span>
            </div>

            {/* Desktop Menu */}
            <div className="hidden md:flex items-center gap-6">
              <button
                onClick={() => router.push('/app')}
                className="text-gray-300 hover:text-white transition-colors"
              >
                Features
              </button>
              <button className="text-gray-300 hover:text-white transition-colors">
                Pricing
              </button>
              <button
                onClick={() => router.push('/app')}
                className="bg-gradient-to-r from-purple-600 to-pink-600 px-6 py-2 rounded-lg font-semibold hover:opacity-90 transition-opacity"
              >
                Get Started
              </button>
            </div>

            {/* Mobile Menu Button */}
            <button
              className="md:hidden"
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            >
              {mobileMenuOpen ? <X /> : <Menu />}
            </button>
          </div>
        </div>

        {/* Mobile Menu */}
        {mobileMenuOpen && (
          <div className="md:hidden border-t border-gray-800 bg-black">
            <div className="px-4 py-4 space-y-3">
              <button className="block w-full text-left text-gray-300 hover:text-white">
                Features
              </button>
              <button className="block w-full text-left text-gray-300 hover:text-white">
                Pricing
              </button>
              <button
                onClick={() => router.push('/app')}
                className="block w-full bg-gradient-to-r from-purple-600 to-pink-600 px-6 py-2 rounded-lg font-semibold text-center"
              >
                Get Started
              </button>
            </div>
          </div>
        )}
      </nav>

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-4">
        <div className="max-w-6xl mx-auto text-center">
          <div className="inline-block mb-6 px-4 py-2 bg-purple-900/30 border border-purple-500/30 rounded-full">
            <span className="text-sm text-purple-300">
              ✨ Loved by 10,000+ high-performers
            </span>
          </div>

          <h1 className="text-6xl md:text-8xl font-bold mb-6 leading-tight">
            get things done
            <br />
            <span className="bg-gradient-to-r from-purple-400 via-pink-500 to-purple-600 bg-clip-text text-transparent">
              with AI ✅
            </span>
          </h1>

          <p className="text-xl md:text-2xl text-gray-400 mb-12 max-w-3xl mx-auto">
            10x your productivity by harnessing AI to manage everyday tasks.
            <br />
            <span className="text-white font-semibold">winners work smarter, not harder</span>
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <button
              onClick={() => router.push('/app')}
              className="group bg-gradient-to-r from-purple-600 to-pink-600 px-8 py-4 rounded-xl font-bold text-lg hover:scale-105 transition-transform shadow-2xl shadow-purple-500/50 flex items-center gap-2"
            >
              Start Creating Tasks
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </button>
            <div className="text-sm text-gray-500">
              <div>⚡ Setup in 2 minutes</div>
              <div>🎯 No credit card required</div>
            </div>
          </div>

          {/* Social Proof */}
          <div className="mt-16 flex flex-wrap justify-center gap-8 text-gray-400 text-sm">
            <div className="flex items-center gap-2">
              <Check className="w-4 h-4 text-green-500" />
              10,000+ active users
            </div>
            <div className="flex items-center gap-2">
              <Check className="w-4 h-4 text-green-500" />
              100,000+ tasks completed
            </div>
            <div className="flex items-center gap-2">
              <Check className="w-4 h-4 text-green-500" />
              4.9/5 rating
            </div>
          </div>
        </div>
      </section>

      {/* Not For Everyone Section */}
      <section className="py-20 px-4 bg-gradient-to-b from-purple-900/20 to-black">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-block mb-6 px-6 py-3 bg-red-900/20 border border-red-500/30 rounded-full">
            <span className="text-red-400 font-bold">#NotForEveryone</span>
          </div>

          <h2 className="text-4xl md:text-6xl font-bold mb-6">
            built for the top 0.01%,
            <br />
            <span className="bg-gradient-to-r from-yellow-400 to-orange-500 bg-clip-text text-transparent">
              the doers and the dreamers
            </span>
          </h2>

          <p className="text-xl text-gray-400 mb-8">
            you never give up, and neither do we.
            <br />
            make every task, every goal, and every dream a reality
          </p>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-20 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              join the{' '}
              <span className="bg-gradient-to-r from-purple-400 to-pink-600 bg-clip-text text-transparent">
                TaskAI revolution
              </span>{' '}
              🎉
            </h2>
            <p className="text-xl text-gray-400">
              an AI-first approach that completely ushers in a new era of task management
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-8">
            {features.map((feature, idx) => (
              <div
                key={idx}
                className="group bg-gradient-to-br from-gray-900 to-black border border-gray-800 rounded-2xl p-8 hover:border-purple-500/50 transition-all hover:scale-105"
              >
                <div className="bg-gradient-to-r from-purple-600 to-pink-600 w-14 h-14 rounded-xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                  <feature.icon className="w-7 h-7 text-white" />
                </div>
                <h3 className="text-2xl font-bold mb-3">{feature.title}</h3>
                <p className="text-gray-400 text-lg">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section className="py-20 px-4 bg-gradient-to-b from-black to-purple-900/20">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              simple, transparent{' '}
              <span className="bg-gradient-to-r from-green-400 to-blue-500 bg-clip-text text-transparent">
                pricing
              </span>
            </h2>
            <p className="text-xl text-gray-400">invest in your productivity</p>
          </div>

          <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            {/* Free Plan */}
            <div className="bg-gray-900 border border-gray-800 rounded-2xl p-8">
              <div className="mb-6">
                <h3 className="text-2xl font-bold mb-2">Free Plan</h3>
                <div className="text-4xl font-bold mb-4">
                  $0<span className="text-lg text-gray-400">/month</span>
                </div>
              </div>
              <ul className="space-y-3 mb-8">
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-green-500" />
                  Up to 5 tasks
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-green-500" />
                  Basic AI features
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-green-500" />
                  Morning routine planner
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-green-500" />
                  Task analytics
                </li>
              </ul>
              <button
                onClick={() => router.push('/app')}
                className="w-full bg-gray-800 hover:bg-gray-700 py-3 rounded-xl font-semibold transition-colors"
              >
                Get Started Free
              </button>
            </div>

            {/* Premium Plan */}
            <div className="bg-gradient-to-br from-purple-900 to-pink-900 border-2 border-purple-500 rounded-2xl p-8 relative overflow-hidden">
              <div className="absolute top-4 right-4 bg-yellow-500 text-black px-3 py-1 rounded-full text-sm font-bold">
                POPULAR
              </div>
              <div className="mb-6">
                <h3 className="text-2xl font-bold mb-2">Premium</h3>
                <div className="text-4xl font-bold mb-4">
                  $9.99<span className="text-lg text-gray-300">/month</span>
                </div>
              </div>
              <ul className="space-y-3 mb-8">
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-green-400" />
                  <strong>Unlimited tasks</strong>
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-green-400" />
                  Advanced AI features
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-green-400" />
                  Priority support
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-green-400" />
                  Real-time insights
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-green-400" />
                  AI chat assistant
                </li>
              </ul>
              <button
                onClick={() => router.push('/app')}
                className="w-full bg-white text-purple-900 hover:bg-gray-100 py-3 rounded-xl font-bold transition-colors"
              >
                Upgrade to Premium
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-20 px-4">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl md:text-5xl font-bold text-center mb-4">
            frequently asked questions 🤔
          </h2>
          <p className="text-center text-gray-400 mb-12">
            have more questions? reach out to us anytime
          </p>

          <div className="space-y-4">
            {faqs.map((faq, idx) => (
              <div
                key={idx}
                className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden"
              >
                <button
                  onClick={() => setFaqOpen(faqOpen === idx ? null : idx)}
                  className="w-full px-6 py-4 text-left flex items-center justify-between hover:bg-gray-800/50 transition-colors"
                >
                  <span className="font-semibold text-lg">{faq.q}</span>
                  <span
                    className={`transform transition-transform ${
                      faqOpen === idx ? 'rotate-180' : ''
                    }`}
                  >
                    ▼
                  </span>
                </button>
                {faqOpen === idx && (
                  <div className="px-6 py-4 border-t border-gray-800 text-gray-400">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 bg-gradient-to-r from-purple-900/30 to-pink-900/30">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-4xl md:text-6xl font-bold mb-6">
            ready to 10x your{' '}
            <span className="bg-gradient-to-r from-yellow-400 to-orange-500 bg-clip-text text-transparent">
              productivity?
            </span>
          </h2>
          <p className="text-xl text-gray-400 mb-8">
            join thousands of high-performers who are already using AI to get things done.
            <br />
            start your journey today
          </p>
          <button
            onClick={() => router.push('/app')}
            className="bg-gradient-to-r from-purple-600 to-pink-600 px-12 py-4 rounded-xl font-bold text-xl hover:scale-105 transition-transform shadow-2xl shadow-purple-500/50"
          >
            Start Creating Tasks
          </button>
          <div className="mt-6 flex flex-wrap justify-center gap-6 text-sm text-gray-500">
            <div>⚡ setup in 2 minutes</div>
            <div>❌ cancel anytime</div>
            <div>✅ trusted by 10k+ users</div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-800 py-12 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col md:flex-row justify-between items-center gap-8">
            <div className="flex items-center gap-2">
              <Sparkles className="w-6 h-6 text-purple-500" />
              <span className="text-xl font-bold">TaskAI Pro</span>
            </div>
            <div className="text-gray-400 text-sm">
              © 2025 TaskAI Pro. All rights reserved.
            </div>
            <div className="flex gap-6 text-sm text-gray-400">
              <button className="hover:text-white transition-colors">Privacy</button>
              <button className="hover:text-white transition-colors">Terms</button>
              <button className="hover:text-white transition-colors">Contact</button>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
